name: Setup and Greet
description: Greeting composite action

inputs:
  name:
    description: Name of the user
    required: true

  language:
    description: Greeting language
    default: en

outputs:
  greeted:
    description: Greeting done
    value: true

runs:
  using: "composite"

  steps:
    - name: Print Greeting
      shell: bash
      run: |
        if [ "${{ inputs.language }}" = "en" ]; then
          echo "Hello ${{ inputs.name }}"
        elif [ "${{ inputs.language }}" = "es" ]; then
          echo "Hola ${{ inputs.name }}"
        else
          echo "Hello ${{ inputs.name }}"
        fi

    - name: Show Runner Info
      shell: bash
      run: |
        echo "Runner OS: $RUNNER_OS"
        echo "Date: $(date)"

    - name: Set Output
      shell: bash
      run: |
        echo "greeted=true" >> $GITHUB_OUTPUT