name: Deploy After Tests

on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - run: echo "Deploying application..."

  fail-handler:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'

    steps:
      - run: echo "Tests failed. Deployment skipped."