name: Docker Build and Push
#test from branch
on:
  push:
    branches:
      - main
      - "*" # Trigger on all branches to build images with commit SHA tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: build docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-app:latest ./app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/github-actions-app:sha-$SHORT_SHA ./app

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' # Only log in on main branch to push images
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main' # Only push on main branch
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/github-action-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/github-action-app:sha-$SHORT_SHA