name: Hosted Runners

on:
  push:

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print runner details
        run: |
          echo "OS: $RUNNER_OS"
          hostname
          whoami

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Print runner details
        run: |
          echo OS: %RUNNER_OS%
          hostname
          whoami

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Print runner details
        run: |
          echo "OS: $RUNNER_OS"
          hostname
          whoami

  check-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Check Docker version
        run: docker --version

      - name: Check Python version
        run: python --version

      - name: Check Node version
        run: node --version

      - name: Check Git version
        run: git --version