name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
jobs:
    print-input:
        runs-on: ubuntu-latest
        steps:
          - name: Print environment input
            run: 'echo "Deploying to environment: ${{ github.event.inputs.environment }}"'