name: Self Hosted Runner

on:
  workflow_dispatch:
  #push:

jobs:
  run-on-self-hosted:
    runs-on: my-linux-runner

    steps:
      - name: Show hostname
        run: hostname

      - name: Show working directory
        run: pwd

      - name: Create test file
        run: |
          echo "Hello from self hosted runner" > runner-test.txt
          ls -la